import { defineConfig, globalIgnores } from "eslint/config";
import nextVitals from "eslint-config-next/core-web-vitals";
import nextTs from "eslint-config-next/typescript";
import prettier from "eslint-config-prettier/flat";

const eslintConfig = defineConfig([
  ...nextVitals,
  ...nextTs,
  // Formatting is Prettier's job; turn off ESLint rules that would fight it.
  prettier,
  {
    // Playwright fixtures call `use()`, which isn't a React hook.
    files: ["e2e/**"],
    rules: { "react-hooks/rules-of-hooks": "off" },
  },
  // Keep linting source/config/tests, not documentation, assets, or generated output.
  globalIgnores([
    // Default ignores of eslint-config-next:
    ".next/**",
    "out/**",
    "build/**",
    "dist/**",
    "next-env.d.ts",
    // Documentation, static assets, and local tooling metadata.
    "**/*.md",
    "docs/**",
    "public/**",
    ".agents/**",
    ".codex/**",
    ".vscode/**",
    // Dependencies and caches.
    "node_modules/**",
    ".yarn/**",
    ".cache/**",
    ".turbo/**",
    ".vercel/**",
    ".husky/_/**",
    // Generated by the Supabase CLI.
    "lib/supabase/database.types.ts",
    "supabase/.temp/**",
    "supabase/.branches/**",
    // Test output.
    "coverage/**",
    "playwright-report/**",
    "test-results/**",
    "blob-report/**",
    "playwright/.cache/**",
  ]),
]);

export default eslintConfig;
