// Writes .env.local from the running local Supabase stack.
// Usage: npm run env:local (after `npm run db:start`)
import { execFileSync } from "node:child_process";
import { writeFileSync } from "node:fs";

const output = execFileSync(
  "supabase",
  [
    "status",
    "-o",
    "env",
    "--override-name",
    "api.url=NEXT_PUBLIC_SUPABASE_URL",
    "--override-name",
    "auth.publishable_key=NEXT_PUBLIC_SUPABASE_PUBLISHABLE_KEY",
  ],
  { encoding: "utf8", stdio: ["ignore", "pipe", "inherit"], shell: process.platform === "win32" },
);

const lines = output
  .split(/\r?\n/)
  .filter((line) => line.startsWith("NEXT_PUBLIC_SUPABASE_"));

if (lines.length !== 2) {
  console.error("Couldn't read Supabase status. Is the local stack running? Try `npm run db:start`.");
  process.exit(1);
}

writeFileSync(".env.local", `# Generated by \`npm run env:local\`\n${lines.join("\n")}\n`);
console.log("Wrote .env.local");
